sudo: false
language: node_js
node_js:
- '10'
branches:
  only:
  - master
before_deploy:
  - npm run build
  - ./build-config.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: master
